### ISSUE TITLE
Would it be possible to relicense libpci under LGPL?

### ISSUE THREAD

**Issue by zschroeder6212** [pciutils/pciutils#131]
Hello,
I am wondering if there is any possibility that libpci specifically could be relicensed under a slightly more permissive LGPL or similar license so that proprietary programs can still link to it. This seems to be a pretty common convention for similar libraries such as libusb, libnvme, etc.

I obviously want to respect the developers, and it's not my intent to open a can of worms with this request. I feel like it would end up enriching the community, since not all developers(or their employers) are willing to release their code under a GPL license.

**Comment by gollux** [comment]
We probably cannot change the license, since it would require all contributors to agree, including some who did not reply to bug reports in their code for years.

**Comment by zschroeder6212** [comment]
That makes sense. Thanks for the response

**Comment by zschroeder6212** [comment]
Are all of the contributors listed on github, or are there others?

**Comment by guillemj** [comment]
Hi!

I think contributions before git might be recorded as Thanks in the ChangeLog or the commit messages, but @gollux would know best here.

It would have been nice to add a link to this issue, and perhaps request a public reply (here or on a mailing list) to keep a public record of who might or might not agree to the change.

One potential issue with a LGPL libpci and GPL for the other code is when wanting to refactor code or move it around.

In the email you mentioned the desire to split libpci out of pciutils? But that does not seem clear from here. Of course that'd be up to @gollux, but if this ever happens it would be nice that the versions of the split projects do not get reset, so that in distributions we do not need to use a version epoch.

And finally, while this would allow some proprietary projects to link against this library, it might not convince people that do not want any (L)GPL on their systems. And perhaps those should be using libpciaccess instead which has a permissive license already?

In any case for my part, I don't think my changes are really of relevance, but if needed I would not mind a switch to LGPL, if that's what the project wants to move to.

**Comment by gollux** [comment]
For the record, here is my reply to a private e-mail by @zschroeder6212:

First, I did not agree with any relicencing. I only expressed serious doubt
that even if I agreed, it would be possible to achieve.

Second, it is damn hard to identify all contributors. The pciutils predate
Git by almost a decade. Even though I used CVS for version control since
the first public release (and all this history is quite well imported as
Git history), the commits do not record authorship of all pieces faithfully.
It would require serious digging in two decades old archives of my mail
to identify all contributors.

Third, some of the important contributors are known to reply to no mail
in past few years. Even for a simple question like "should I still consider
you the maintainer of this back-end" went unanswered. So I seriously doubt
that you have a chance of getting any answer.

For the record, I still think that GPL is a good license for libpci.
In particular, I have no motivation for allowing proprietary code based
on libpci. I could be convinced by a strong example, but I do not think
it is likely.
